name: "Daily dev :: Publish"

on:
  schedule:
    - cron: "0 4 * * *" # 4am UTC everyday
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/kubesmarts_daily_dev_publish.yml"
      - ".github/workflows/kubesmarts_build_and_publish.yml"

jobs:
  build_and_publish:
    uses: ./.github/workflows/kubesmarts_build_and_publish.yml
    with:
      dry_run: false
      environment: dev
      tag: main
    secrets:
      kie_group_tools_token: ${{ secrets.KIE_GROUP_TOOLS_TOKEN }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
