name: "Custom version :: Build and Publish"

on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        default: true
      environment:
        description: Environment for the workflow (dev, staging, prod)
        required: true
        default: dev
      tag:
        description: Tag to build
        required: false
        default: main

concurrency:
  group: kubesmarts-custom-build-publish-${{ github.event.inputs.environment }}
  cancel-in-progress: true

jobs:
  build_and_publish:
    uses: ./.github/workflows/kubesmarts_build_and_publish.yml
    with:
      dry_run: ${{ fromJSON(github.event.inputs.dry_run) }}
      environment: ${{ github.event.inputs.environment }}
      tag: ${{ github.event.inputs.tag }}
    secrets:
      kie_group_tools_token: ${{ secrets.KIE_GROUP_TOOLS_TOKEN }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
