name: "CI :: OSL :: Publish Images Snapshots"

on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        required: true
      KOGITO_VERSION:
        description: "Specify the version for Kogito Runtime"
        required: false
        default: "999-SNAPSHOT"
      IMAGE_TAG:
        description: "Specify the tag for the images"
        required: false
        default: "main"

jobs:
  publish_images_snapshots:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout @ GitHub default"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.IMAGE_TAG }}

      - name: "Exporting KOGITO_RUNTIME_version"
        run: |
          if [ -n "${{ github.event.inputs.KOGITO_VERSION }}" ]; then
            echo "KOGITO_RUNTIME_version=${{ github.event.inputs.KOGITO_VERSION }}" >> $GITHUB_ENV
          else
            echo "No KOGITO_VERSION input provided. Keeping the default or existing behavior."
          fi

      - name: "Exporting OSL_IMAGE_TAG"
        run: |
          if [ -n "${{ github.event.inputs.IMAGE_TAG }}" ]; then
            echo "OSL_IMAGE_TAG=${{ github.event.inputs.IMAGE_TAG }}" >> $GITHUB_ENV
          elif [ -n "${{ github.event.inputs.KOGITO_VERSION }}" ]; then
            echo "OSL_IMAGE_TAG=${{ github.event.inputs.KOGITO_VERSION }}" >> $GITHUB_ENV
          else
            echo "OSL_IMAGE_TAG=main" >> $GITHUB_ENV
          fi

      - name: "Verify Exported Variables"
        run: |
          echo "KOGITO_RUNTIME_version: $KOGITO_RUNTIME_version"
          echo "OSL_IMAGE_TAG: $OSL_IMAGE_TAG"

      - name: "Setup environment"
        uses: ./.github/actions/setup-env

      - name: "Cache Maven repository"
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: "Setup kie-tools repository"
        # TODO: use this
        # uses: ./.github/actions/setup-kie-tools
        uses: kubesmarts/kie-tools/.github/actions/setup-kie-tools@SRVLOGIC-611-Web-tools-images-use-apache-snapshot-kogito-runtimes-artifacts
        with:
          KOGITO_VERSION: ${{ github.event.inputs.KOGITO_VERSION }}
          DEPS_BRANCHNAME: ${{ github.event.inputs.IMAGE_TAG }}
          ENABLE_BUILD_DEPS_REPOSITORIES: true
          PNPM_FILTER: ${{ vars.IMAGES_UPSTREAM_PNPM_FILTER }}

      - name: "Build Images"
        env:
          DROOLS_AND_KOGITO__skip: true
          KIE_TOOLS_BUILD__buildContainerImages: "true"
          KIE_TOOLS_BUILD__runEndToEndTests: "false"
          KIE_TOOLS_BUILD__runTests: "false"
          # TODO: on upstream implement a root-env named defaultRegistry and defaultAccount and change on every image package
          SONATAFLOW_BUILDER_IMAGE__registry: "quay.io"
          SONATAFLOW_BUILDER_IMAGE__account: "kubesmarts"
          SONATAFLOW_DEVMODE_IMAGE__registry: "quay.io"
          SONATAFLOW_DEVMODE_IMAGE__account: "kubesmarts"
          SONATAFLOW_MANAGEMENT_CONSOLE__registry: "quay.io"
          SONATAFLOW_MANAGEMENT_CONSOLE__account: "kubesmarts"
          KOGITO_DATA_INDEX_EPHEMERAL_IMAGE__registry: "quay.io"
          KOGITO_DATA_INDEX_EPHEMERAL_IMAGE__account: "kubesmarts"
          KOGITO_DATA_INDEX_POSTGRESQL_IMAGE__registry: "quay.io"
          KOGITO_DATA_INDEX_POSTGRESQL_IMAGE__account: "kubesmarts"
          KOGITO_JOBS_SERVICE_EPHEMERAL_IMAGE__registry: "quay.io"
          KOGITO_JOBS_SERVICE_EPHEMERAL_IMAGE__account: "kubesmarts"
          KOGITO_JOBS_SERVICE_POSTGRESQL_IMAGE__registry: "quay.io"
          KOGITO_JOBS_SERVICE_POSTGRESQL_IMAGE__account: "kubesmarts"
          SERVERLESS_LOGIC_WEB_TOOLS__swfBuilderImageRegistry: "quay.io"
          SERVERLESS_LOGIC_WEB_TOOLS__swfBuilderImageAccount: "kubesmarts"
          SERVERLESS_LOGIC_WEB_TOOLS__baseBuilderImageRegistry: "quay.io"
          SERVERLESS_LOGIC_WEB_TOOLS__baseBuilderImageAccount: "kubesmarts"
          SERVERLESS_LOGIC_WEB_TOOLS__swfDevModeImageRegistry: "quay.io"
          SERVERLESS_LOGIC_WEB_TOOLS__swfDevModeImageAccount: "kubesmarts"
          SONATAFLOW_QUARKUS_DEVUI_VERSION: ${{ github.event.inputs.KOGITO_VERSION }}
          DASHBUILDER__viewerImageRegistry: "quay.io"
          DASHBUILDER__viewerImageAccount: "kubesmarts"
          SONATAFLOW_OPERATOR__registry: "quay.io"
          SONATAFLOW_OPERATOR__account: "kubesmarts"
          KOGITO_DB_MIGRATOR_TOOL_IMAGE__registry: "quay.io"
          KOGITO_DB_MIGRATOR_TOOL_IMAGE__account: "kubesmarts"

        run: >-
          eval "pnpm ${{ vars.IMAGES_UPSTREAM_PNPM_FILTER }} --workspace-concurrency=1 build:prod"

      - name: "Login to Quay"
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_ACCOUNT }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: "Push Images to Quay"
        if: ${{ !inputs.dry_run }}
        run: |
          # TODO: remove this
          exit 1
          for image in ${{ vars.PUBLISH_IMAGES_LIST }}; do
            echo "Pushing $image to Quay"

            if [ "${{ env.OSL_IMAGE_TAG }}" = "main" ]; then
              echo "OSL_IMAGE_TAG is 'main'. Pushing main tag."
              docker push quay.io/kubesmarts/$image:main || { echo "Failed to push $image:main"; exit 1; }
            else
              echo "OSL_IMAGE_TAG is not 'main'. Tagging and pushing snapshot."
              docker tag quay.io/kubesmarts/$image:main quay.io/kubesmarts/$image:${{ env.OSL_IMAGE_TAG }}
              docker push quay.io/kubesmarts/$image:${{ env.OSL_IMAGE_TAG }} || { echo "Failed to push $image with tag $OSL_IMAGE_TAG to Quay"; exit 1; }
            fi
          done
